version: "3.7"

services:
  mongo:
    container_name: mongo
    image: mongo:4-xenial
    ports:
      - 27017:27017
    networks:
      - java_network
  redis:
    container_name: redis
    image: redis:5
    ports:
      - 6379:6379
    networks:
      - java_network
  java-docker:
    container_name: java-docker
    image: java-docker:1.0
    ports:
      - 8080:8080
    depends_on:
      - redis
      - mongo
    # environment variable
    environment:
      - NAME=Docker
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - java_network
#create network
networks:
  java_network:
    name: java_network
#create and start: docker-compose up -d (-d: mode daemon)
#stop and remove: docker-compose down
#stop: docker-compose stop
#start: docker-compose start (running container yang sudah ada)
