version: "3"
services:
  pg_master:
    build: ./master
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=admin
    networks:
      default:
        aliases:
          - pg_cluster
  pg_slave:
    build: ./slave
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=admin
      - PG_REP_USER=rep
      - PG_REP_PASSWORD=admin
      - PG_MASTER_HOST=pg_master
    networks:
      default:
        aliases:
          - pg_cluster
volumes:
  pg_data:
