version: "3.7"

services:
  mongo:
    image: mongo:4-xenial
    container_name: mongo
    restart: always
    volumes:
      - /home/improject/SERVER/data/mongo/db/:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    ports:
      - 27017:27017
    # networks:
    # - improject_network
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
